#environment:
#  matrix:

branches:
  only:
    - master

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

#install:

build_script:
  - ps: tree C:\mingw-w64

#test_script:
