#environment:
#  matrix:

branches:
  only:
    - master

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

#install:

build_script:
  - SET PATH=C:\msys64\mingw32\bin;%PATH%
  - gcc --version
  - cd r123
  - mingw32-make

#test_script:
