#environment:
#  matrix:

branches:
  only:
    - master

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

#install:

build_script:
  - SET PATH=C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\bin;%PATH%
  - gcc --version
  - ps: tree C:\msys64

#test_script:
