#environment:
#  matrix:

branches:
  only:
    - master

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

#install:

build_script:
  - ps: ls C:\msys64\mingw32\bin
  - ps: ls C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin
  - ps: ls C:\MinGW\bin
  - SET PATH=C:\msys64\mingw32\bin;%PATH%
  - gcc --version
  - cd r123
  - make

#test_script:
